version: "3.8"
services: 
  react:
    container_name: "react"
    build: ./client
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - SERVER_HOST=http://localhost
  flask:
    build: ./server
    container_name: flask
    restart: always
    environment:
      - APP_NAME=Ebudget_Server
      - POSTGRES_HOST=db:5432
      - POSTGRES_PASSWORD=jinyeeU
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ebudget
  nginx: 
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
  
  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=jinyeeU
      - POSTGRES_DB=ebudget
    volumes:
      - pgdata:/var/lib/postgresql/data
    expose:
      - 5432
volumes:
  pgdata: