# TODO cannot load postgres uri to server
version: "3.8"
services: 
  flask:
    build: ./server
    container_name: flask
    restart: always
    environment:
      - APP_NAME=Ebudget_Server
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    expose:
      - 8080
    
  nginx: 
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
  
  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=jinyeeU
      - POSTGRES_DB=ebudget
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
